---
- name: ensure resolv.conf
  file:
    src: "/run/systemd/resolve/stub-resolv.conf"
    dest: "/etc/resolv.conf"
    state: link
    force: true
  become: true
  when: systemd_resolved_override_resolv_conf
