---
- name: ensure resolv.conf
  file:
    src: "{{ systemd_resolv_conf_file }}"
    dest: "/etc/resolv.conf"
    state: link
    force: true
  become: true
  when: systemd_resolved_override_resolv_conf
